services:
  hass-blocks:
    container_name: hass-blocks
    build:
      context: ./automations
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base:latest
        BUILD_TYPE: local
    volumes:
      - ./automations/src:/src
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3020:3001"
    restart: unless-stopped
    privileged: true

  hass-blocks-frontend:
    container_name: hass-blocks-frontend
    build:
      context: ./hass-blocks-frontend
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base:latest
        BUILD_TYPE: local
    volumes:
      - ./hass-blocks-frontend/logs:/var/log
      - ./hass-blocks-frontend/src:/src
      - ./hass-blocks-frontend/mongo-data:/data
      - ./hass-blocks-frontend/failed-insert:/failed-insert
      - /etc/localtime:/etc/localtime:ro

    environment:
      NEXT_PUBLIC_LEGO_PORT: 3020
      NODE_ENV: development
    ports:
      - "8080:3000"
      - "27017:27017"
    restart: unless-stopped
    privileged: true
