services:
  homeassistant:
    container_name: homeassistant-bens-flat
    build: ./Dockerfile.test
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
