name: "Hass Blocks Frontend"
description: "Visualisation of Hass Blocks automations"
ingress_entry: "/bdd5e753_hass-blocks-frontend/ingress"
version: "1.0.22"
slug: "hass-blocks-frontend"
homeassistant_api: true
ingress: true
network_mode: host
init: false
environment:
  NODE_ENV: production
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
