name: "Hass Blocks Frontend"
description: "Visualisation of Hass Blocks automations"
version: "1.0.0"
slug: "hass-blocks-frontend"
hassio_role: default
homeassistant_api: true
ingress: true
ingress_port: 3040
webui: "http://[HOST]:[PORT]/"
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
