name: "Hass Blocks Frontend"
description: "Visualisation of Hass Blocks automations"
version: "1.0.39"
slug: "hass-blocks-frontend"
homeassistant_api: true
hassio_api: true
ingress: true
network_mode: host
init: false
map:
  - config:rw

ingress_port: 3000

environment:
  IN_ADDON: "true"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
