name: "Hass Blocks"
description: "Building blocks for Home Assistant"
version: "1.0.2"
slug: "hass-blocks"
homeassistant_api: true
host_network: false
init: false
ports:
  - 3001/tcp: 3001
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
