name: "Hass Blocks"
description: "Building blocks for Home Assistant"
version: "1.0.2"
slug: "hass-blocks"
hassio_role: default
homeassistant_api: true
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
